[package]
name = "sweetmcp-pingora"
version = "0.3.1"
edition = "2021"
description = "SweetMCP Server • Sugora gateway (Pingora 0.5, OTEL, Unix-socket CLI)"
authors = ["SweetMCP Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/sweetmcp/server"
readme = "README.md"
keywords = ["mcp", "gateway", "proxy", "pingora", "opentelemetry"]
categories = ["network-programming", "web-programming", "api-bindings"]

[dependencies]
# Core Pingora dependencies - using latest from GitHub main branch
pingora = { git = "https://github.com/cloudflare/pingora", package = "pingora", features = ["proxy", "lb"] }
pingora-proxy = { git = "https://github.com/cloudflare/pingora", package = "pingora-proxy" }
pingora-load-balancing = { git = "https://github.com/cloudflare/pingora", package = "pingora-load-balancing" }

# CLI argument parsing
clap = { version = "4.5", features = ["derive"] }

# Async runtime
tokio = { version = "1.46", features = ["macros", "rt-multi-thread", "sync", "fs", "net", "time", "signal"] }

# MCP SDK - removed, using sweetmcp-axum instead
sweetmcp-axum = { path = "../sweetmcp-axum" }

# Protocol parsing
async-graphql = { version = "7", features = ["tracing"] }
async-graphql-value = "7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
capnp = "0.21"

# Authentication & Security
jsonwebtoken = "9.3"
ring = "0.17"
uuid = { version = "1.17", features = ["v4", "serde"] }
hex = "0.4"

# Observability
opentelemetry = { version = "0.30", features = ["trace", "metrics"] }
opentelemetry_sdk = { version = "0.30", features = ["trace", "metrics"] }
opentelemetry-prometheus = "0.29"
opentelemetry-jaeger = "0.22"
prometheus = { version = "0.14", features = ["process"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.31"

# System monitoring
sysinfo = { version = "0.35", features = ["multithread"] }

# Configuration & Environment
env_logger = "0.11"
log = "0.4"
dotenvy = "0.15"
config = { version = "0.15", features = ["yaml", "toml"] }

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Utilities
once_cell = "1.21"
dirs = "5.0"
seahash = "4.1"
bytes = "1.10"
base64-url = "3.0"
base64 = "0.22"
prometheus-parser = "0.4"

# Lock-free performance optimizations
arc-swap = "1.7"                # Lock-free atomic operations on Arc
atomic-counter = "1.0"          # Atomic counters for statistics

# HTTP client for peer communication
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "json", "stream"] }

# DNS resolver for service discovery
hickory-resolver = { version = "0.25", features = ["tokio"] }

# Rate limiting
governor = "0.10"
nonzero_ext = "0.3"

# Additional security
time = { version = "0.3", features = ["serde", "macros", "formatting"] }
rand = "0.9"
url = "2.5"
rustls = { version = "0.23", features = ["std"] }
rustls-pemfile = "2.2"
rcgen = { git = "https://github.com/rustls/rcgen", branch = "main", features = ["pem"] }
hostname = "0.4"
sodiumoxide = "0.2"
x509-parser = { version = "0.17", features = ["verify"] }
zeroize = { version = "1.8.1", features = ["derive"] }
age = { version = "0.11.1", features = ["armor"] }
webpki = { version = "0.22.4", features = ["std"] }
pem = "3.0"
der = { version = "0.7", features = ["derive", "oid", "std"] }
x509-cert = { version = "0.2", features = ["builder"] }
x509-ocsp = { version = "0.2", default-features = false }

# Feature-gated dependencies
futures = "0.3"
pin-project = "1.1"
sweetmcp-workspace-hack = { version = "0.1", path = "../sweetmcp-workspace-hack" }

[dev-dependencies]
# Testing framework
tokio-test = "0.4"
proptest = "1.7"
criterion = { version = "0.6", features = ["html_reports"] }
tempfile = "3.20"
wiremock = "0.6"

# Load testing
hyper = { version = "1.6", features = ["full"] }
tower = "0.5"

[features]
default = ["production"]
production = ["tracing-subscriber/registry"]
development = ["tracing-subscriber/fmt"]
testing = []

# Benchmarks will be added later
# [[bench]]
# name = "protocol_parsing"
# harness = false

# [[bench]]
# name = "load_balancing"
# harness = false

[lib]
name = "sweetmcp"
path = "src/lib.rs"

[[bin]]
name = "sweetmcp_server"
path = "src/main.rs"
