[workspace]
resolver = "2"
members = [
    "sweetmcp-axum",
    "sweetmcp-pingora", 
    "sweetmcp-daemon",
    "sweetmcp-memory",
    # WebAssembly plugins - now properly configured with extism-pdk 1.4.1
    "plugins/arxiv",
    "plugins/browser",
    "plugins/eval-js",
    "plugins/eval-py", 
    "plugins/eval-rs",
    "plugins/eval-sh",
    "plugins/fetch",
    "plugins/fs",
    "plugins/hash",
    "plugins/ip",
    "plugins/qr-code",
    "plugins/reasoner",
    "plugins/time",
    "sweetmcp-workspace-hack",
]

[workspace.package]
version = "0.1.0"
authors = ["SweetMCP Contributors"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sweetmcp/sweetmcp"
