[workspace]
resolver = "2"
members = [
    "sweetmcp-axum",
    "sweetmcp-pingora", 
    "sweetmcp-daemon",
    "sweetmcp-memory",
    # All plugins are WebAssembly modules that need extism runtime - compile separately
    # "plugins/arxiv",
    # "plugins/browser",
    # "plugins/eval-js",
    # "plugins/eval-py", 
    # "plugins/eval-rs",
    # "plugins/eval-sh",
    # "plugins/fetch",
    # "plugins/fs",
    # "plugins/hash",
    # "plugins/ip",
    # "plugins/qr-code",
    # "plugins/reasoner",
    # "plugins/time",
    "sweetmcp-workspace-hack",
]

[workspace.package]
version = "0.1.0"
authors = ["SweetMCP Contributors"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sweetmcp/sweetmcp"

[workspace.dependencies]
# Common dependencies with latest versions
tokio = { version = "1.45.1", features = ["full"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.98"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
thiserror = "2.0.12"
clap = { version = "4.5.40", features = ["derive"] }
log = "0.4.27"
env_logger = "0.11.8"
chrono = "0.4.41"
reqwest = { version = "0.12.20", features = ["json"] }
base64 = "0.22.1"
uuid = { version = "1.17.0", features = ["v4", "serde"] }
futures = "0.3.31"
bytes = "1.10.1"
once_cell = "1.21.3"
