[package]
name = "fluent-ai"
description = "Pure Traits & Builders over any AI Framework"
version.workspace = true
edition.workspace = true

[dependencies]

[lib]
name = "fluent_ai"
path = "src/lib.rs"

[dev-dependencies]
