[package]
name = "sweetmcp-claude-desktop-configurator"
version = "0.1.0"
edition = "2021"

[dependencies]
extism-pdk = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]