[package]
name         = "sweetmcp-daemon"
version      = "0.2.0"
edition      = "2021"
license      = "Apache-2.0 OR MIT"

[dependencies]
anyhow               = "1"
chrono               = { version = "0.4", features = ["serde"] }
crossbeam-channel    = "0.5"
env_logger           = "0.11"
log                  = "0.4"
nix                  = { version = "0.30", default-features = false, features = ["fs", "process", "signal", "user"] }
once_cell            = "1"          # one‑time global config
serde                = { version = "1", features = ["derive"] }
serde_json           = "1"
toml                 = "0.8"
systemd = { version = "0.10", optional = true }
clap         = { version = "4.5", features = ["derive"] }   # for the new CLI
which        = "8"                                         # locate system executables
exec = "0.3.1"
dirs = "6.0.0"
thiserror   = "2.0.12"
cfg-if      = "1.0.1"
base64      = "0.22.1"
flate2      = { version = "1.1.2", default-features = false, features = ["rust_backend"] }
async-recursion = "1.1.1"

# Auto-configuration support
sweetmcp-client-autoconfig = { path = "../sweetmcp-client-autoconfig" }

# async support (always enabled)
async-process = { version = "2.3" }
tokio         = { version = "1.46.0", features = ["process", "macros", "signal", "rt-multi-thread", "time", "fs"] }

# SSE server dependencies (always enabled)
axum          = { version = "0.7" }
tower         = { version = "0.5" }
tower-http    = { version = "0.6", features = ["cors", "trace"] }
reqwest       = { version = "0.12", features = ["json"] }
regex         = { version = "1.0" }
url           = { version = "2.0" }
uuid          = { version = "1.17", features = ["v4"] }
tracing       = { version = "0.1" }
async-stream  = { version = "0.3" }
futures-util  = { version = "0.3" }
serde_urlencoded = { version = "0.7" }
rcgen = "0.14"
sweetmcp-workspace-hack = { version = "0.1", path = "../sweetmcp-workspace-hack" }
futures = "0.3.31"
tokio-stream = "0.1.17"

# Zero-allocation performance optimizations  
arrayvec = { version = "0.7", features = ["serde"] }          # Fixed-size arrays without heap allocation
memmap2 = { version = "0.9" }           # Memory-mapped file I/O for zero-copy access
atomic-counter = { version = "1.0" }    # Lock-free atomic counters
tokio-util = { version = "0.7" }        # Tokio utilities for cancellation
dashmap = { version = "6.1" }           # Lock-free concurrent hash maps
memchr = { version = "2.7" }            # SIMD-accelerated string matching
fastrand = "2.3.0"
jwalk = "0.8.1"
rayon = "1.10.0"
walkdir = "2.5.0"

[features]
default = []
systemd-notify = ["systemd"]
systemd = ["dep:systemd"]

# platform-specific deps
[target.'cfg(target_os = "linux")'.dependencies]
users = "0.11.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi  = { version = "0.3", features = ["processthreadsapi", "winnt", "handleapi", "securitybaseapi"] }
windows = { version = "0.61", features = [
  "Win32_Foundation",
  "Win32_Security",
  "Win32_System_Threading",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging"
] }

[target.'cfg(target_os = "macos")'.dependencies]
plist  = "1.7.2"
zip    = { version = "4.2.0", default-features = false, features = ["deflate"] }

[build-dependencies]
pkg-config = "0.3.32"
tauri-macos-sign = "2.1.0"
cc = "1.2"
tempfile = "3.20"
which = "8.0"
zip = { version = "4.2.0", default-features = false, features = ["deflate"] }
# Dependencies needed for build scripts
jwalk = "0.8.1"
rayon = "1.10.0"
fastrand = "2.3.0"
