[package]
name = "sweetmcp_memory"
version = "0.1.0"
edition = "2024"
description = "Cognitive Memory System with quantum-inspired routing and emergent evolution"
authors = ["David Maple<david@cyrup.ai>"]
license = "MIT"

[dependencies]
# SurrealDB and its features
surrealdb = { version = "2.3", features = ["http", "protocol-http", "kv-surrealkv", "kv-mem"] }

# Async runtime
tokio = { version = "1.46", features = ["full"] }
futures = { version = "0.3" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

# Utilities
uuid = { version = "1.17", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = { version = "2.0" }
anyhow = { version = "1.0" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
reqwest = { version = "0.12", features = ["json"] }
bincode = { version = "2.0" }
prometheus = { version = "0.14" }

# Cognitive system dependencies
rand = { version = "0.9" }
base64 = { version = "0.22" }
ndarray = { version = "0.16" }
nalgebra = { version = "0.33", features = ["serde-serialize"] }
petgraph = { version = "0.8" }
ordered-float = { version = "5.0" }
dashmap = { version = "6.1" }
async-channel = { version = "2.3" }

# Missing dependencies for cognitive features
sha2 = { version = "0.10" }
walkdir = { version = "2.5" }
num_cpus = { version = "1.17" }
num-complex = { version = "0.4" }

# Zero-allocation performance optimizations
arrayvec = { version = "0.7" }          # Fixed-size arrays without heap allocation
smallvec = { version = "1.13" }         # Small vectors that avoid heap allocation
heapless = { version = "0.8" }          # Collections without heap allocation

# Optional vector store implementations
faiss = { version = "0.12.1", optional = true }
hnsw = { version = "0.11.0", optional = true }

# HTTP API (optional)
axum = { version = "0.8", optional = true }
tower = { version = "0.5", optional = true }
tower-http = { version = "0.6", features = ["cors", "trace"], optional = true }
sweetmcp-workspace-hack = { version = "0.1", path = "../sweetmcp-workspace-hack" }
async-stream = "0.3.6"
crossbeam-channel.workspace = true
parking_lot.workspace = true

[dev-dependencies]
# Testing
mockall = { version = "0.13" }
mockito = { version = "1.7" }
assert_approx_eq = { version = "1.1" }
criterion = { version = "0.6" }
tempfile = { version = "3.20" }
rand = { version = "0.9" }
gix = { version = "0.72" }
async-trait = { version = "0.1" }

[features]
default = ["surreal-vector", "openai-embeddings", "cognitive", "quantum-routing", "evolution", "api"]
api = ["axum", "tower", "tower-http"]
faiss-vector = ["faiss"]
hnsw-vector = ["hnsw"]
surreal-vector = []
openai-embeddings = []
custom-embeddings = []
cognitive = []
quantum-routing = ["cognitive"]
evolution = ["cognitive"]
full-cognitive = ["cognitive", "quantum-routing", "evolution"]

[[bench]]
name = "memory_benchmarks"
harness = false

[[bench]]
name = "python_comparison_bench"
path = "benches/python_comparison_bench.rs"
harness = false

[[example]]
name = "basic_usage"
path = "examples/basic_usage.rs"

[[example]]
name = "memory_types"
path = "examples/memory_types.rs"

[[example]]
name = "async_patterns"
path = "examples/async_patterns.rs"

[lib]
name = "sweetmcp_memory"
path = "src/lib.rs"
