[package]
name = "sweetmcp-client-autoconfig"
version = "0.1.0"
edition = "2021"

[dependencies]
# File watching with latest watchexec
watchexec = "8.0.1"
watchexec-filterer-globset = "8.0.0"
watchexec-events = "6.0.0"
watchexec-signals = "5.0.0"
miette = "7.6.0"

# Config file handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"

# Core utilities
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tokio = { version = "1", features = ["full"] }
directories = "6.0.0"
crossbeam-channel = "0.5.15"
parking_lot = "0.12.4"

# Plugin system
extism = "1.11.1"
extism-pdk = "1.4.1"
sweetmcp-workspace-hack = { version = "0.1", path = "../sweetmcp-workspace-hack" }

# Workspace hack

# Platform-specific features
[target.'cfg(windows)'.dependencies]
winreg = "0.55.0"

[target.'cfg(target_os = "macos")'.dependencies]
plist = "1.7.2"

[lib]
name = "sweetmcp_client_autoconfig"
path = "src/lib.rs"


[features]
dirs = []
