name = "sweetmcp-autoconfig"
description = "Automatic MCP client configuration service"
service_type = "autoconfig"
command = "sweetmcp-autoconfig"  # This is handled internally
auto_restart = true

[health_check]
enabled = true
interval_s = 300  # Check every 5 minutes

# This service watches for MCP client installations and automatically
# configures them to use SweetMCP. Zero configuration required!